name: Format Check

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  clang-format-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install clang-format
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-format
      - name: Check format
        run: |
          make check-format CLANG_FORMAT_BIN=clang-format