name: Guard: forbid language-level plusplus

on:
  push:
  pull_request:

jobs:
  guard-no-plusplus:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run no-"++" grammar guard
        shell: bash
        run: bash scripts/guard_no_plusplus.sh
